### ISSUE TITLE
Changing portrait facing flips incorrectly

### ISSUE THREAD

**Issue by chrisgregan** [FungusGames/Fungus#190]
Reported on [the forum](http://fungusgames.com/forum/#!/general:there-is-a-glitch-in-say-di)

**Comment by Blasawebo** [comment]
If anyone want to help, the problem occur when you have a character sprite looking the other direction, and when they talk for a fraction of time they flip for a instance, and they return to their normal self

**Comment by chrisgregan** [comment]
Thanks for the extra info.

**Comment by chrisgregan** [comment]
More info in this [forum post](http://fungusgames.com/forum/#!/general:about-portraits-and-relativ)
