### ISSUE TITLE
Call methods from Fungus and pass/return parameters

### ISSUE THREAD

**Issue by RonanPearce** [FungusGames/Fungus#250]
Make it possible to pass at least one parameter when executing the target method.

Also, the Unity engineers at Unite 2015 helped me figure out how to use the UnityEngine.Events with Fungus so we should add support for that too.

**Comment by RonanPearce** [comment]
We're adding 2 ways to do this.

Using the Unity Event System. This is a fast, standard way of calling script methods but our implementation is limited to passing 1 parameter and can't handle return values.
Using the reflection system in Unity to call a method with multiple parameters and storing returned values in Fungus variables. It's not as efficient as the Unity Event System but very flexible and powerful.
Many thanks to forum user Bigdiddy (http://fungusgames.com/forum/#!/general:fungus-invoke-method-extens) for contributing the Invoke Method command (the 2nd approach above).

**Comment by chrisgregan** [comment]
Added in a previous version of Fungus
