### ISSUE TITLE
Enter player name

### ISSUE THREAD

**Issue by RonanPearce** [FungusGames/Fungus#254]
Add a new Fungus command which displays a simple modal dialog asking the player to enter a string value. Typically use case would be requesting the player to enter their name.

**Comment by RonanPearce** [comment]
(Comment from csfalcao)
:+1:

**Comment by RonanPearce** [comment]
I think the name changing feature could just copy the behavior found in most Gameboy/DS/3DS RPGs, like Play Final Fantasy Tactics, see a example here, at 1 56: UEOkKwCoW4M?t=1m56s.

**Comment by csfalcao** [comment]
Glad it's coming

**Comment by chrisgregan** [comment]
We added an Enter Name example in an earlier version of Fungus

**Comment by csfalcao** [comment]
(y) Congrats
