### ISSUE TITLE
miss init commandIndex  when block is created  dynamically

### ISSUE THREAD

**Issue by flashmouse** [FungusGames/Fungus#290]
Hi I have discussed how to create commands dynamically in the website http://fungusgames.com/forum/ and finally I decided to do it by create a csv file and write a tool to create a full flowchart.
   It works fine in unity editor but it has something wrong when it runs on real android device.I do some test and find that Block.cs file sets all commands commandIndex in Awake() function.
   On android device Awake() function will execute immediately after flowchart.CreateBlock() executed.And all commands are added  to the block's commandList after this block created so that no commands get right commandIndex unless the first one.
   I now write another Init() function in Block.cs.The function is the same code with Awake() function and I execute Init() by myself so it would execute right.
   Or you have better method to resolve my problem?
   Thank you!

**Comment by chrisgregan** [comment]
I think that's a good solution, though I'd call the function something more descriptive like SetCommandIndices().

If you want to send this change through as a pull request I can merge it in?

The csv tool sounds interesting too!

**Comment by flashmouse** [comment]
I'm glad to help to provide code,thank you! I'll pull reguest a later.

About csv tool,it's just a temporary solution and in http://fungusgames.com/forum/ , chrisgregan said that this project is doing a plan(https://trello.com/c/RBDlHD8D/5-define-command-list-in-spreadsheet) to resolve this problem?

**Comment by chrisgregan** [comment]
This issue was fixed in #320.

We're planning something like the CSV command list in Fungus 3. We're thinking to use LUA scripting to provide maximum flexibility.
