### ISSUE TITLE
_FungusState not removed when Fungus removed from project

### ISSUE THREAD

**Issue by unknowndevice** [FungusGames/Fungus#318]
I don't know if this is an issue any more since I'm using a slightly older version of Fungus. But when you remove Fungus from your project _FungusState remains as hidden object in the scene and prints out MonoBehaviour Missing when you run your project.

**Comment by chrisgregan** [comment]
Thanks for the bug report. I don't know how we'd fix this though? There's no callback we could hook into when a script is being deleted. Obviously if the Fungus scripts have been deleted then we can't run any code to fix the issue. Open to suggestions!

**Comment by chrisgregan** [comment]
Closing this one as there's no real way to fix it.

**Comment by Tymski** [comment]
How to delete the file and where it is?

**Comment by Tymski** [comment]
If someone has the same problem I found a quick fix:
Open the Scene in a text editor, replace all occurrences of  `m_ObjectHideFlags: 1` with `m_ObjectHideFlags: 0`. Now the hidden object will be visible and you can delete it in the hierarchy.
