### ISSUE TITLE
Faulty indent levels when inspector is not displayed

### ISSUE THREAD

**Issue by Moshimo** [FungusGames/Fungus#380]
My understanding is that command indentation is updated **if and only if** the inspector and flowchart window are visible. See _Fungus/Flowchart/Editor/BlockEditor.cs_

```
public virtual void DrawBlockGUI(Flowchart flowchart)
{
	[...]
	UpdateIndentLevels(block);
	[...]
}
```
If the block is not shown in the inspector (i.e. when launching the build from the executable outside unity/maximize on play/etc) it may happen that a block command indentation would not be updated resulting in a faulty parsing of commands. It has indeed happened to me in a (very long) block.
I (temporarly) solved by copying the UpdateIndentLevel method in the _Block.cs_ and invoking it in the Execute method right before starting the ExecuteBlock coroutine:
```
public virtual bool Execute(Action onComplete = null)
{
	if (executionState != ExecutionState.Idle)
	{
		return false;
	}
	if (!executionInfoSet)
	{
		SetExecutionInfo();
	}
	executionCount++;
	UpdateIndentLevels();
	StartCoroutine(ExecuteBlock(onComplete));
	return true;
}
```

**Comment by chrisgregan** [comment]
Thanks for the bug report. I guess we should do a step at startup to ensure that the indent levels are correct. Will look into it!
