### ISSUE TITLE
Fungus Commands not recognized: Fungus scans wrong assembly?

### ISSUE THREAD

**Issue by scrapcupcake** [FungusGames/Fungus#381]
So, wrote up a simple fungus command, and been pulling my hair out figuring out why it isn't showing up in my flowchart window; Fungus being open source I've dived into the code, started debugging, and found the following. 

First, by modifying `EditorExtensions.FindDereivedTypes` to give me a simple debug:

```
	    public static System.Type[] FindDerivedTypes(System.Type baseType, bool classOnly = true)
	    {
            var asmbl = System.Reflection.Assembly.GetAssembly(baseType);
            Debug.Log("Assembly?! " + asmbl.FullName);
            return FindDerivedTypesFromAssembly(asmbl, baseType, classOnly);
	    }
```

I found the following results:
Above call's Assembly: Assembly-CSharp-firstpass
My own code: Assembly-CSharp
My own Editor code: Assembly-CSharp-Editor

So, when Fungus scans for commands, it only gets things in the Assembly-CSharp-firstpass assembly, and I have no idea why it would end up there vs. the other two; Time to google, but thought I'd report what I've found so far in case someone knows what's up already.

**Comment by scrapcupcake** [comment]
And it was my collaborator not realizing that Unity treats the 'Plugin' folder as super special, dooming us to chasing this down! 

For anyone else that comes across this, here's your answer: Move Fungus OUT of your Plugins folder. It does not belong there. Unless something specifically tells you to install it to Plugins DO NOT install it to Plugins. That is all :D

**Comment by chrisgregan** [comment]
Glad you got it sorted out. Yeah, you gotta watch out for those reserved folder names in Unity. Another one is Resources, anything inside a Resources folder will be copied straight in your build without any checks to see if it's used by a scene or not. Very useful if you know that's what it's for!

**Comment by AcademyOfF** [comment]
I have the same exact problem, but this didn't fix it for me.  After modifying my code like the OP did (including renaming Plugins to Libraries), I see this output:

https://imgur.com/PHdW27G

But, my additional commands are not in that Assembly file and they do not show up in the list of commands.  How do I tell Fungus to scan all assembly files for commands, or tell it exactly which ones to scan?

**Comment by AcademyOfF** [comment]
OK, i figured it out by doing this:

```
        public static System.Type[] FindDerivedTypes(System.Type baseType, bool classOnly = true)
        {
            //return FindDerivedTypesFromAssembly(System.Reflection.Assembly.GetAssembly(baseType), baseType, classOnly);
            System.Type[] result = new System.Type[0];
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                result = result.Concat(FindDerivedTypesFromAssembly(assembly, baseType, classOnly)).ToArray();
            }
            return result;
        }
```

No idea why I had to do that but the OP didn't have to.  I feel like I'm doing something wrong.  Is Fungus **not** supposed to use Assembly Definition files?
