### ISSUE TITLE
Private variable values being reset with multiple flowcharts

### ISSUE THREAD

**Issue by chrisgregan** [FungusGames/Fungus#389]
Reported on [the forum](http://fungusgames.com/forum/#!/support-questions:issue-with-custom-command)

**Comment by protototo** [comment]
I think it's not variable values being reset, but SetVariable command field values.

**Comment by chrisgregan** [comment]
I tracked this down to a weird behaviour in the inspector code, it was trying to inspect a variable on the wrong Flowchart. Committing the fix now.
