### ISSUE TITLE
Localisation export not working

### ISSUE THREAD

**Issue by chrisgregan** [FungusGames/Fungus#392]
Reported on [the forum](http://fungusgames.com/forum/#!/general:tutorial-for-importing-and)

**Comment by Screenhog** [comment]
[Test Fungus.zip](https://github.com/FungusGames/Fungus/files/178498/Test.Fungus.zip)

Since my other project was quite big and contained some sensitive material, I made a test project. It's much smaller, but it's exhibiting the same symptoms.

**Comment by Screenhog** [comment]
How was GDC? Have you had a chance to look at this yet?

**Comment by chrisgregan** [comment]
Hey Screenhog! GDC was awesome, some amazing talks and met lots of indie developers who are using Fungus.

Thanks for sending over the zip file. Here's what I've found.
1. The reason you're seeing a language string in the exported keys is because you've got "en" set as the localisation id for one of your flowcharts. You can use this property to set a custom id for the flowchart, if it's blank it defaults to using the name of the Flowchart gameobject.

2. Standard Text import seems to be working fine for me. I recorded a quick [demo video](https://drive.google.com/file/d/0B_HM8CiuDPG7d0kxUlJXcElPZkE/view?usp=sharing)

If the process I'm doing above isn't working for you then it must be related to your dev environment. Are you developing on Windows? What version of Unity are you running?

**Comment by Screenhog** [comment]
So... I've had good customer support before, but I've never had a product
send a personalized video showing the fix in progress. And for a product
that our company didn't even pay for?! Above and beyond.

I've tested the fix on my real project, and it does work for the import and
export of text. I removed the "en" from the flowchart fields, and it seems
to be working as expected now. However, eventually the project will need
language localization, so I may be calling on you again when that time
comes.

**Comment by chrisgregan** [comment]
Our goal with Fungus is simply to make a high quality tool with a vibrant
community around it. We make good money doing consultancy work based off
the recognition we get for that, so I'm happy to provide a bit of support
when needed. The community are great at helping each other out too so it's
not as much work as you might think. The bug reports on the forum really
help us to improve the software so keep them coming.

Good luck with the project!
